# syntax=docker/dockerfile:1.7

# Stage 1: Download all dependencies
FROM ubuntu:24.04 AS dependencies

ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
ENV TZ=Etc/UTC
ARG VCPKG_FEED_URL
ARG VCPKG_FEED_USERNAME
ARG VCPKG_BINARY_SOURCES
ENV VCPKG_BINARY_SOURCES=${VCPKG_BINARY_SOURCES}

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
	apt-get update && apt-get install -y --no-install-recommends cmake git \
	unzip build-essential ca-certificates curl zip unzip tar \
	pkg-config ninja-build autoconf automake libtool glibc-tools \
	python3 mono-complete tzdata \
	&& ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime \
	&& echo "${TZ}" > /etc/timezone \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt
COPY vcpkg.json /opt
RUN vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ' | tr -d '\r\n') \
	&& echo "vcpkg commit ID: '$vcpkgCommitId'" \
	&& git clone https://github.com/microsoft/vcpkg.git \
	&& cd vcpkg \
	&& git fetch origin \
	&& git checkout "$vcpkgCommitId" \
	&& ./bootstrap-vcpkg.sh

# Install dependencies using manifest mode standalone
WORKDIR /opt/vcpkg_manifest
COPY vcpkg.json /opt/vcpkg_manifest/

RUN --mount=type=cache,target=/opt/vcpkg/downloads \
	--mount=type=cache,target=/opt/vcpkg/buildtrees \
	--mount=type=cache,target=/opt/vcpkg/packages \
	--mount=type=cache,target=/root/.cache/vcpkg \
	export VCPKG_FORCE_SYSTEM_BINARIES=1; \
	/opt/vcpkg/vcpkg install --x-manifest-root=/opt/vcpkg_manifest --x-install-root=/opt/vcpkg_installed --triplet=arm64-linux --host-triplet=arm64-linux

# Stage 2: create build
FROM dependencies AS build
RUN apt-get update && apt-get install -y --no-install-recommends cmake ninja-build zip unzip tar pkg-config curl \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /srv/build
COPY src ./src
COPY cmake ./cmake
COPY tests ./tests
COPY recompile.sh CMakeLists.txt CMakePresets.json vcpkg.json ./
# Copy the vcpkg_installed directory from dependencies stage
COPY --from=dependencies /opt/vcpkg_installed ./vcpkg_installed

RUN export VCPKG_MANIFEST_INSTALL=OFF && export VCPKG_INSTALLED_DIR=/srv/build/vcpkg_installed && ./recompile.sh "/opt"


# Stage 3: execute
FROM ubuntu:24.04 AS prod
COPY --from=build /srv/build/canary /srv/canary/canary
WORKDIR /srv/canary
ENTRYPOINT ["/srv/canary/start.sh", "canary"]

